(defun makekings (theBoard)
  (dotimes (x 2)
    (dotimes (c 8)
      (let ((p (boarditemat theboard (list (* 7 x) c))))
        (if (eq 'piece (type-of p))
            (if (not (eq (slot-value p 'owner) x))
                (setf (slot-value p 'isKing) t)
              )
          )
        )
      )
    )
  )